name: Sync Git to SVN

on:
  push:
    branches: ['master']

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: echo "VPNC_GATEWAY=${{ secrets.VPNC_GATEWAY }}" >> /tmp/.env
    - run: echo "VPNC_ID=${{ secrets.VPNC_ID }}" >> /tmp/.env
    - run: echo "VPNC_SECRET=${{ secrets.VPNC_SECRET }}" >> /tmp/.env
    - run: echo "VPNC_USERNAME=${{ secrets.VPNC_USERNAME }}" >> /tmp/.env
    - run: echo "VPNC_PASSWORD=${{ secrets.VPNC_PASSWORD }}" >> /tmp/.env

    - run: docker run --rm -v $(pwd):/thesis --workdir /tmp --privileged --env-file /tmp/.env --dns 8.8.8.8 masterodin/vpnc:latest "svn ${SVN_AUTH} co https://svn3.cs.rpi.edu/rair/papers/2020.Peveler.Thesis/thesis && /bin/cp -R /thesis /tmp && pushd /tmp/thesis && svn status && { if [ \"$(svn status | grep -c '^?')\" -gt 0 ]; then svn status | grep '^?' | sed 's/?    //' | xargs svn add ; fi ; } && svn ${SVN_AUTH} commit -m 'git sync'"
      env:
        SVN_AUTH: --username ${{ secrets.RPI_USERNAME }} --password ${{ secrets.RPI_PASSWORD }}
