name: Git SVN Sync

on:
  push:
    branches: ['master']

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: masterodin/action-vpnc@master
      with:
        gateway: ${{ secrets.VPNC_GATEWAY }}
        id: ${{ secrets.VPNC_ID }}
        secret: ${{ secrets.VPNC_SECRET }}
        username: ${{ secrets.VPNC_USERNAME }}
        password: ${{ secrets.VPNC_PASSWORD }}
        command: uname -a

    # - run: svn co --non-interactive --no-auth-cache --username ${{ secrets.RPI_USERNAME }} --password ${{ secrets.RPI_PASSWORD }} https://svn3.cs.rpi.edu/rair/papers/2020.Peveler.Thesis/thesis
